# %{game_title} base configuration file

# Game network configuration.
[net]

  # Interface is the address you want the server to bind to. By default it's
  # "localhost" but it can also be set to "0.0.0.0" as well or another IP address
  # to be accessible from outside the server.
  interface = "localhost"

  # Change the port the game runs on
  port = 8080

  # Change the port the server private port runs on. This private port is only
  # connectable from the machine hosting the server and is the only way to send
  # 'SERVER' messages to all memebers of the game. Other than this, it's the same
  # as connecting to the standard port.
  # TODO: Assess necessity.
  # private_port = 8081

# log contains settings specific to the logger for the project such as maximum
# log level and output targets.
[log]

  level = "debug"

  # Define log targets
  # Log type consist of 'os' and 'file'. The 'os' types can have a target of
  # 'stdout' and 'stderr' while the target of the 'file' types should be either
  # a relative path to the log file or absolute path. Multiple log targets are
  # supported.
  [[log.targets]]

    type = "os"
    target = "stdout"

# Configure the connection information to Neo4j. You can use any environment
# name you want as you can specify which environment to execute when running
# the server. This connects to the default username and password of Neo4j.
[database.development]

  authentication = true
  host = "localhost"
  port = "7474"
  username = "neo4j"
  password = "neo4j"
  connection_max = 10
