# DragonDetails base file

# Game network configuration.
[net]

# Change the port the game runs on
game_port = 8080
# Change the port the server private port runs on. This private port is only
# connectable from the machine hosting the server and is the only way to send
# 'SERVER' messages to all memebers of the game. Other than this, it's the same
# as connecting to the standard port.
private_port = 8081

# log contains settings specific to the logger for the project such as maximum
# log level and output targets.
[log]

  level = "debug"

  # Define log targets
  # Log type consist of 'os' and 'file'. The 'os' types can have a target of
  # 'stdout' and 'stderr' while the target of the 'file' types should be either
  # a relative path to the log file or absolute path. Multiple log targets are
  # supported.
  [[log.targets]]

    type = "os"
    target = "stdout"

# Configure the database. For a list of supported databases please check the
# wiki. The default database is SQLite.
[database.development]

  adapter = "sqlite3"
  dbname = "{{GameName}}.db3"

  # adapter = "mysql"
  # adapter = "postgres"

  # user = ""
  # password = ""
  # dbname = "{{GameName}}"

  # sslmode is only for postgres databases
  # sslmode = "disable"
